### ISSUE TITLE
Reducing number of images per class

### ISSUE THREAD

**Issue by Deepak-** [beckgom/cifar-10-parser#1]
Thank you for this amazing script! This is actually not an issue, but I want to reduce the number of images per class. So instead of 5,000 images per class in the training set, I want 1,000.  How can I achieve this objective?

Thanks again!

**Comment by Akhila001** [comment]
Even i have the same issue.Can someone tell me how to solve the issue?

**Comment by beckgom** [comment]
hey, I changed the code a little. as @Deepak- said, it is not an actual issue, I made branch. just check it out.
